### PR TITLE
Update Personal Data Stores section about Solid.

### PR DESCRIPTION
**Pull request by csarven**
Changes in this PR updates information about Personal Data Stores section about Solid to more accurately reflect definitions and current development.

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
👍 Looks good.

**Review by acoburn — APPROVED** [review]
👍🏼

**Comment by andorsk** [comment]
WG reviewed. No issues with the language. Need to validate that there is no issues with membership contribution.

**Comment by andorsk** [comment]
Will try to get this merged before our meeting today

**Comment by andorsk** [comment]
Follow up on this: No issues with PR, am back channeling the membership issue. If there's a better forward will let you know. 

@csarven  just a heads up:

**Comment by csarven** [comment]
How about this way forward:

---

I, [Sarven Capadisli](https://csarven.ca/#i), hereby release my contribution in [this Pull Request](https://github.com/decentralized-identity/decentralized-web-node/pull/298) ([archived](https://web.archive.org/web/20240515194549/https://github.com/decentralized-identity/decentralized-web-node/pull/298/commits/d4f6eeb4cdf78dac25a30d3fa1d7f3c33c54b0b9#diff-bdafe2c8c89467bd79b23affca6284f4001365056df791173b761347d6924061)) to the public domain and grant unrestricted usage rights to [Decentralized Identity Foundation](https://identity.foundation/) for incorporation into the [Decentralized Web Node Companion Guide](https://https://identity.foundation/decentralized-web-node/guide).

---

Let me know if an adjustment to the text above would make it easier for you. Feel free to add me as a contributor of some sort somewhere without necessarily implying I endorse the work.

**Comment by andorsk** [comment]
@csarven I believe this will work. Also talked with @acoburn and noted that they are in DIF now. We will try to merge today.

**Comment by andorsk** [comment]
Thanks for being patient on this @csarven . Obviously we are just trying to protect our members. We should have this in today.

**Comment by csarven** [comment]
What's the relevancy of @acoburn or "they" (?) to my contribution in this PR where I also took the initiative to make it public domain?

You're welcome.

**Comment by andorsk** [comment]
@csarven merging in. Discussed at the group today. Non-normative and should be fine.

**Pull request merged**
