### PR TITLE
Update spec.md

### PR DESCRIPTION
**Pull request by TallTed**
I think the unencoded parameters for each URL should be listed in their own right, and encoded within the URLs -- partly but not only because I cannot tell what should be encoded and what should be as shown, which is why I'm not putting my entire suggestion in directly.  I have added evil extra spaces to each line that is likely to be impacted, so they show up as "suggestible" in the Github web interface.

### CODE REVIEW

**Comment by TallTed** [comment]
I have no idea why this #74 now "cannot be rebased due to conflicts", as I just resolved the conflicts that were present, and now cannot even see the conflicts.  I will leave this open pending resolution of #79 (which I created based on comments in a review which hadn't posted before merge of #78, not realizing until I'd created #79 that this #74 was still pending)...

**Comment by csuwildcat** [comment]
@TallTed I got that strange message too for a recent PR, but it went away went I switched branches and started clean.

**Comment by TallTed** [comment]
Largely overtaken by events, this PR is now reduced to a corrected syntax name (`json5`->`json`) for code-fenced syntax highlighting.

**Comment by OR13** [comment]
Conflicts exist.

**Comment by TallTed** [comment]
@OR13 -- Conflicts resolved.

**Comment by TallTed** [comment]
@OR13 -- Except now (after posting the above "Conflicts resolved" comment) it says --

> This branch cannot be rebased due to conflicts

-- which conflicts the GitHub site won't reveal to me.

Re-done in #171.  Please don't leave that for another year.

**Pull request closed without merging**
