### PR TITLE
added JSON schemas for DWN specification

### PR DESCRIPTION
**Pull request by andorsk**
Adding JSON Schemas for DWN Objects compliant with the specifications. Sharing for visibility, however this is a working PR. Do NOT merge yet.

### CODE REVIEW

**Comment by andorsk** [comment]
@csuwildcat any thoughts on something like this. There's some missing pieces (I'll do soon), but wanted some early feedback before committing too hard on this direction.

**Comment by csuwildcat** [comment]
Let's make sure the spec reflects the current state before you dump more time in.

**Comment by andorsk** [comment]
Thanks @csuwildcat . Let's discuss over the DIF call tomorrow. Thought was this was a starting point, and we can modify off this PR until it's ready.

**Comment by andorsk** [comment]
https://github.com/TBD54566975/dwn-sdk-js/tree/main/json-schemas can probably be copied over here and leveraged to update this. I will do that soon.

**Review by LiranCohen — COMMENTED** [review]
Not in expert in JSON Schema, so I'm just skimming this to make sure they make sense to me, and then will drill on them individually.

First thing that caught my attention were two interfaces defined here that we don't have within the spec, Events and Messages. Are these missing from the spec or just mistakenly included?

**Comment by andorsk** [comment]
@csuwildcat @thehenrytsai  @mistermoe can one of you review this PR and let us know if there's any issues with merging this? 

We would like to merge this by next DWN call if possible.

**Comment by LiranCohen** [comment]
Looked a little deeper into the DWN implementation that uses this. Seems this is a part of sync.
Should we define these interfaces in the spec w/ a TODO as far as the specific behavior?

I'd like for the sections and these definitions to somewhat be up to date with each other.

**Review by thehenrytsai — APPROVED** [review]
There was a recent update to [RecordsQuery](https://github.com/TBD54566975/dwn-sdk-js/pull/393/files#diff-5b94016cb0329ae66e5d778d38f84e13d0fd489a15778d34cf297c6ecfd5e95f), otherwise looks good to me.

**Pull request merged**
